name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on:  ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.19.12

    - name: Clang
      run: |
          apt search clang
          # sudo apt-get install -f -y clang llvm
          # TODO: add different clang versions
          sudo apt-get install -f -y llvm-11 clang-11
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-11 2000
          # view priority
          sudo update-alternatives --config clang
          # view version
          clang --version

    - name: Lint
      run: |
          ./scripts/lint.sh
    - name: Run coverage
      run: |
          go get -u github.com/wadey/gocovmerge
          go get -u github.com/Konstantin8105/cs
          go get -u golang.org/x/sys/unix
          go test -race -coverprofile=coverage.txt -covermode=atomic
          # TRAVIS=true ./scripts/test.sh
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
          file: coverage.txt
          name: codecov-umbrella # optional
          verbose: true # optional (default = false)
          token: ${{ secrets.CODECOV_ORG_TOKEN }}

    - name: Build
      run: |
          go mod download
          go build -v

    - name: Race test
      run: go test -run=TestIntegrationScripts/tests/ctype.c -race -v -timeout=30m
