name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on:  ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Clang
      run: |
          sudo apt-get install -f -y clang llvm
          clang --version

    - name: Lint
      run: |
          ./scripts/lint.sh

    - name: Coverage
      run: |
          go mod download
          # go get -u github.com/wadey/gocovmerge
          # go get -u github.com/Konstantin8105/cs
          # go get -u golang.org/x/sys/unix
          # ./scripts/test.sh
          # go test ./...
          # include_cov=coverage.txt bash <(curl -s https://codecov.io/bash)
          go test -timeout=30m -tags integration -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload coverage to Codecov
      run: include_cov=coverage.txt bash <(curl -s https://codecov.io/bash)

    - name: Build
      run: |
          go mod download
          go build -v ./...

    - name: Race test
      run: go test -tags=integration -run=TestIntegrationScripts/tests/ctype.c -race -v
