name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
          go mod download
          go build -v ./...

    - name: Lint
      run: |
          ./scripts/lint.sh

    - name: Coverage
      env: 
          CLANG: 12
      run: |
          #sudo apt install -f -y --force-yes llvm
          # wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          # sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          # sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-$CLANG main"
          # sudo apt-get install lzip ## Added for scripts/ed.sh
          # sudo apt-get update
          # sudo apt-cache search clang
          # sudo apt-get install -f -y --force-yes clang-$CLANG lldb-$CLANG libmad0-dev
          clang --version
          go mod download
          # go get -u -v github.com/wadey/gocovmerge
          # go get -u -v github.com/Konstantin8105/cs
          # go get -u -v golang.org/x/sys/unix
          # ./scripts/test.sh
          # include_cov=coverage.txt bash <(curl -s https://codecov.io/bash)
