name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
          go mod download
          go build -v ./...

#   - name: Test
#     run: go test -cover ./...


    - name: Lint
      run: |
          ./scripts/lint.sh

    - name: Coverage
      run: |
          sudo apt install -f -y --force-yes llvm
          go mod download
          go get -u -v github.com/wadey/gocovmerge
          go get -u -v github.com/Konstantin8105/cs
          go get -u -v golang.org/x/sys/unix
          ./scripts/test.sh
          include_cov=coverage.txt bash <(curl -s https://codecov.io/bash)
